version: "3.9"
services:
  node1:
    build: .
    # network_mode "host" does not work on mac, need to map ports manually
    # network_mode: "host"
    ports:
      - "5001:5001"
      - "4001:4001"
    environment:
      # TODO: Use docker secrets for password
      PASSWORD: 1234
      KEYSTORE_ID: hnx0rxlhv2bsovj65xu2w4oz682xbeo1hfakad3jhheh2qzlbfm01nq7w38vcauz
      REST_ADDRESS: 127.0.0.1:5001
      P2P_ADDRESS: 127.0.0.1:4001
      BOOT_NODE: 127.0.0.1:4001
    # keystore and datastore are found in /keystore and /datastore of the container
    volumes:
      - ${HOME}/.keystore:/keystore
      - ${HOME}/.datastore:/datastore
  node2:
    build: .
    ports:
      - "5002:5002"
      - "4002:4002"
    environment:
      PASSWORD: 1234
      KEYSTORE_ID: hnx0rxlhv2bsovj65xu2w4oz682xbeo1hfakad3jhheh2qzlbfm01nq7w38vcauz
      REST_ADDRESS: 127.0.0.1:5002
      P2P_ADDRESS: 127.0.0.1:4002
      BOOT_NODE: 127.0.0.1:4001
    volumes:
      - ${HOME}/.keystore:/keystore
      - ${HOME}/.datastore2:/datastore
